### ISSUE TITLE
redirect loop on invalid single-user auth token

### ISSUE THREAD

**Issue by minrk** [jupyter/jupyterhub#119]
when the single-user server's API request fails with 403, it's handled as failed login (302) causing a redirect loop, when it should be handled as "500: oh noes, I can't do anything!"

**Comment by ssanderson** [comment]
Oooooh...I've definitely hit this before without realizing it.  Makes sense now.

**Comment by minrk** [comment]
This one happens when restarting/resetting the Hub, invalidating the API token used to check cookies. If that API token is invalidated, the single-user server is defunct and has to be restarted.

It's not the *only* cause of redirect loops - they seem to be the symptom of almost any misbehavior in single-user login, but it's at least one I can reproduce and explain.

**Comment by ssanderson** [comment]
Yeah, I think I've hit this with Dockerspawner with the following sequence:

1. Start hub with dockerspawner.
2. Log in and spawn a single user server.
3. Shut down the hub, allowing it to stop (but not kill) any running containers.
4. Restart hub and login as same user as before.  Dockerspawner will restart the exited container rather than create a new one, which then triggers a redirect loop because the tokens are out of sync.

It's possible that there's a step or two I'm missing in there.

**Comment by minrk** [comment]
Yup, that's exactly right. The same sequence *should* be fine if the Hub state database persists from one Hub session to the next.

**Comment by minrk** [comment]
Should be fixed by #121, turning this particular case into a relatively informative 500 error instead of a redirect loop.
