### ISSUE TITLE
Admin UI suggestions

### ISSUE THREAD

**Issue by jhamrick** [jupyter/jupyterhub#141]
As I've been using the admin UI a bit for my class, I just had a few things that I thought would be nice to have/change in it:

* move the "add user" button to the top -- it is annoying with lots of users to have to scroll all the way down to find it
* add some simple statistics at the top of the page: number of running servers, number of currently active users, etc.
* it would be awesome to be able to sort users by the different columns -- admin, alphabetically, by last seen
* currently, if you shut down a user's server, it causes the page to refresh which often jumps you up to the top (or just somewhere else). It would be nice if the update could be done in the background without actually reloading the page.

Obviously, none of these are urgent, but I think they would make the admin experience a little easier. I can open separate issues for them if so desired.

**Comment by minrk** [comment]
All of these are good ideas. I've been trying to do as little in Javascript as possible on JupyterHub, as an experiment in reducing the things I hate about working on IPython. One of the results of that is the user table is computed server-side in jinja instead of client-side. Without changing that, the first two ideas are easy enough to implement. The third can be done with URL params, but that requires reloading the page for each re-sort (maybe not a big deal), and probably *should* be done in Javascript. The last one would be very easy if the table were built with Javascript, but should be feasible anyway.

**Comment by minrk** [comment]
@jhamrick #142 should cover these. The page is still refreshed when users are changed, but not when servers start/stop.
