### ISSUE TITLE
Ipython Profiles and Kernels

### ISSUE THREAD

**Issue by Arttii** [jupyter/jupyterhub#153]
Hi,

So I was wodnering if anyone can clarify is it is possible to use a ipytohn profile with the jupyterhub. If so where do I install it, so its say global and how do I turn it on? I know we can use kernel files, but I would like to use some theme customization I have. 

Help would be appreciated.

**Comment by minrk** [comment]
Configuration with JupyterHub can get pretty confusing, since there are so many layers:

1. JupyterHub config: a single `jupyterhub_config.py`, in the CWD or specified via `jupyterhub -f /path/to/config.py`. This does not affect the configuration of the IPython servers for your users, other than the ability to change the command-line arguments used to start those servers.
2. single-user instances of `ipython notebook`. These can load kernels from:
  - /usr/local/share/jupyter/kernels
  - ~/.ipython/kernels (separate for each user)
3. profiles, which are only a notion of the single-user ipython server, and distinct for each user. You can set the profile for each user in the JupyterHub configuration by adding `'--profile=foo'` to `Spawner.cmd`. This, however, would require you populating the profile directory in every users `~/.ipython` directory. I wouldn't recommend doing this.
4. *IPython* actually has a notion of system-wide config, so you can set defaults for all users. This is the most likely place for JupyterHub admins to put config for their users' IPython instances. You can create and edit the file `/etc/ipython/ipython_notebook_config.py` or `/etc/ipython/ipython_config.py` to set global defaults for all users.

**Comment by Arttii** [comment]
Cheers, it took me a while to figure half of this out through trial and error. Maybe we should document this somehow?
________________________________

**Comment by dsblank** [comment]
On Tue, Feb 24, 2015 at 12:35 PM, Arttii <notifications@github.com> wrote:

> Cheers, it took me a while to figure half of this out through trial and
> error. Maybe we should document this somehow?
>

+1 ... I didn't know that last one.

-Doug

**Comment by minrk** [comment]
Yeah, there are *lots* of docs to write on configuring IPython and JupyterHub. The trick is to balance concise docs and examples that people will actually read with complete docs that cover the many details edge cases that people usually ignore.

**Comment by giacomov** [comment]
Can someone expand on this solution by @minrk :

4. *IPython* actually has a notion of system-wide config, so you can set defaults for all users. This is the most likely place for JupyterHub admins to put config for their users' IPython instances. You can create and edit the file `/etc/ipython/ipython_notebook_config.py` or `/etc/ipython/ipython_config.py` to set global defaults for all users.

I tried creating those files, but they are not read when the python kernel start up from jupyter.

A bit of context: I'm running an Ubuntu server with Jupyter and IPython installed. I want to be able to create a profile which will be read by the python kernels on each startup, for all users of the system. Thus, I cannot use profiles in the home directory of each user.

For example, I want to make "inline" the default backend for matplotlib, so that the users do not need to use the "%matplotlib line" magic every single time.

Thanks!

**Comment by basnijholt** [comment]
Having the same problems at giacomov, could someone comment?

**Comment by giacomov** [comment]
Yes,
I solved it too. 

Apparently the system-wide configuration under /etc/ipython gets used only if the user running the notebook has not set up its own configuration under ~/.ipython/profile_default/.

**Comment by nehalecky** [comment]
Thanks for the discussion on this thread—the closest I've found to the issue I'm having, so I'll ask here and hope that this is landing in the right place. :)

### Jupyter Install
I recently installed versions of Jupyter 1.0.0 and IPython 4.0.0 (via `conda install jupyter`)  on a ubuntu vm, and am trying to perform configuration similar to what was achievable using IPython notebook profiles for similar functionality to what @giacomov desired, such as:
> For example, I want to make "inline" the default backend for matplotlib, so that the users do not need to use the "%matplotlib line" magic every single time.

### Jupyter Config
Following the [Jupyter config documentation](http://jupyter-notebook.readthedocs.org/en/latest/config.html#config), I generated a default config via:
```bash 
:~$ jupyter notebook --generate-config
```
and piecemealing a few other [jupyter configs](https://github.com/minrk/.jupyter/blob/master/jupyter_notebook_config.py), I came up with the following

```python
c = get_config()

starting_imports = ['import pandas as pd',
                    'import seaborn as sns',
                    'from matplotlib import pyplot as plt']
starting_settings = ["sns.set(font='Bitstream Vera Sans')",
                     "sns.set_context('poster', font_scale=1.1)",
                     "sns.set_context({'figure.figsize': [16, 9]})",
                     "plt.ioff()"]
c.InteractiveShellApp.exec_lines = starting_imports + starting_settings

c.InlineBackend.figure_formats = ['svg']
c.InteractiveShellApp.matplotlib = 'inline'
import os
c.NotebookManager.notebook_dir = c.NotebookApp.notebook_dir = os.path.expanduser('~/vm/shared/notebooks')
```

### Jupyter Notebook Launch

I launch Jupyter from the command line as:
```bash 
:~$ jupyter notebook --port=8008 --ip=0.0.0.0  --no-browser --config=/home/vagrant/vm/shared/notebook_config.py
```

This launches without incident, however, when I open a new or used notebook, the only config that manifests is the `.notebook_dir` directive. Nothing else that is described in the config.py above functions as I hoped. With this, how does a jupyter config file pass configuration to the kernel? I'd like to pass this using the ` --config` directive and not rely on the system-wide configuration as described above.

I see others had success using JSON kernel definitions,
>I was able to solve it, see: http://stackoverflow.com/questions/29773954/change-ipython-3-for-python-3-kernel-to-python2-for-the-cluster-too/29798906#29798906
Is this now the only way to perform these configurations? 

FWIW, info about ubuntu box:
```bash
:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

Thanks in advance. I appreciate everyone's efforts. :)

**Comment by maxhodak** [comment]
I'm stuck on this too.

**Comment by IamViditAgarwal** [comment]
@minrk  Is there a way to know which iPython profile has been clicked by the user so that I can run custom functions based on that day?
