### ISSUE TITLE
requirements broken

### ISSUE THREAD

**Issue by shreddd** [jupyter/jupyterhub#181]
Looks like the default jupyterhub notebook spawning mechanism no longer works after the following is changed in requirements.txt:

ipython[notebook]>=3
changed to
ipython>=3

In particular I get the following errors:
ImportError: No module named 'zmq'
ImportError: No module named 'jsonschema'

I'm guessing that pyzmq and jsonschema (and possibly other things) get pulled in as requirements with the ipython[notebook] install so these should be documented in the install process.

Thanks
-Shreyas

**Comment by minrk** [comment]
This is a tricky one, because:

1. in the default case, with local spawners, hub does require ipython and its notebook dependencies
2. in many cases (DockerSpawner, etc.), the Hub part *doesn't* need the notebook dependencies, only base IPython
3. when IPython is installed by a mechanism other than setuptools (e.g. `conda install ipython-notebook`), the `ipython[notebook]` dependency is undefined and unresolvable:

```
(test-extra) $ pip install ipython[notebook]
Requirement already satisfied (use --upgrade to upgrade): ipython[notebook] in ~/env/test-extra/lib/python3.4/site-packages
  Exception:
  Traceback (most recent call last):
    File "~/env/test-extra/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2501, in requires
      deps.extend(dm[safe_extra(ext)])
  KeyError: 'notebook'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "~/env/test-extra/lib/python3.4/site-packages/pip/basecommand.py", line 232, in main
      status = self.run(options, args)
    File "~/env/test-extra/lib/python3.4/site-packages/pip/commands/install.py", line 339, in run
      requirement_set.prepare_files(finder)
    File "~/env/test-extra/lib/python3.4/site-packages/pip/req/req_set.py", line 436, in prepare_files
      req_to_install.extras):
    File "~/env/test-extra/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2504, in requires
      "%s has no such extra feature %r" % (self, ext)
  pip._vendor.pkg_resources.UnknownExtra: ipython has no such extra feature 'notebook'
```

So we have to choose between:

1. depending on ipython[notebook]
  - pulls in unnecessary dependencies for some config (no big deal)
  - impossible to install on some systems (pretty big deal)
  - `pip install jupyterhub` has everything it needs, when it works
2. depend on just `ipython`
  - requires two packages: `pip install ipython[notebook] jupyterhub` to get everything for most basic config
  - doesn't install unnecessary packages when single-user servers are in a different env

If it weren't for the fact that installing IPython without setuptools makes JupyterHub impossible to install, I wouldn't hesitate to make it depend on `ipython[notebook]`. And the 4.0 split of IPython will do away with the extras_require nonsense, so it can go back to depending on the 'real' `jupyter-notebook` package. In the meantime, I am torn between the two choices.

I made the change from `ipython[notebook]` to `ipython` earlier this week, when I personally ran into it, but I think maybe I'll put it back and wait until someone else runs into it. Perhaps using JupyterHub with conda-installed IPython is a rare case.

**Comment by shreddd** [comment]
In the case tweaking the documentation describing the two cases might be sufficient. Alternately, you might consider a couple of alternate requirements.py files. For now I'll plan on adding "pip install ipython[notebook]" to my install scripts.

**Comment by minrk** [comment]
@shreddd yupI think I'll go with `ipython` as a hard dep, and add `ipython[notebook]` to the README for now.
