### ISSUE TITLE
custom user environment variables?

### ISSUE THREAD

**Issue by shreddd** [jupyter/jupyterhub#227]
Is there a recommended way to enable per-user environment variables in jupyterhub? 
Currently there is configuration option `c.Spawner.env_keep` but this only lets you pass in existing variables. 
I'm looking for two things:
1. Set a per user variable that follows a standard pattern. This would be similar to $HOME. eg. $SCRATCH might be /scratch/{username}/
2. Allow users to preset some environment variables in a .rc style config file. This would allow users to spawn their notebooks with a customized environment. eg. with custom PYTHONPATH or LD_LIBRARY_PATH variables

I can probably achieve both these things by wrapping the Spawner.cmd that calls 'jupyterhub-singleuser' in a shell script that sets the environment variables / sources a .rc file but I wanted to check if there were hooks for environment variables coming in future versions jupyterhub.

**Comment by ssanderson** [comment]
> Allow users to preset some environment variables in a .rc style config file. This would allow users to spawn their notebooks with a customized environment. eg. with custom PYTHONPATH or LD_LIBRARY_PATH variables.

@shreddd is allowing users to write a `ipython_notebook_config.py` and/or `ipython_kernel_config.py` and placing it in their ~/.ipython not sufficient for your needs here?

**Comment by minrk** [comment]
You can also set these in a single common `ipython_notebook_config.py` in /etc/ipython, which will be loaded by each single-user server.

**Comment by shreddd** [comment]
The ipython_notebook_config.py seems like the right place for this, but I didn't see any obvious hooks for custom environment variables in ipython_notebook_config.py. Is there a config option for setting environment variables to be handed down to notebooks?

**Comment by minrk** [comment]
It's a Python file, so you can modify `os.environ`. The kernels inherit `os.environ` from the notebook server process, so modifications in the notebook config should propagate to the kernels.

**Comment by shreddd** [comment]
OK - thanks. That should help. Just wanted to make sure there wasn't a config variable I was missing.

**Comment by parmentelat** [comment]
Hi there

I have 2 questions for minrk

 * first, is this mechanism still current ? (I did a quick test but could not see the change get through to the user kernel; if this is supposed to work I will insist more); 

 * second, am I right to assume that this `ipython_notebook_config.py` is loaded as a regular user (and not once and for good by root); I'm saking because I also need `os.environ['HOME']` to have the right value.

Thanks in any case

**Comment by jhamrick** [comment]
Yes, this mechanism should still be current. And I'm pretty sure `$HOME` should always be correct for the user who owns the single user server.

**Comment by minrk** [comment]
@parmentelat you are correct that `[jupyter]_notebook_config.py` is only loaded as the user as part of their server's startup. It is never touched by the Hub user.

**Comment by parmentelat** [comment]
Thanks
Just to confirm that I can see `/etc/jupyter/jupyter_notebook_config.py` loaded by the running kernels (I was stupidly trying with all the names in ìpython` instead of `jupyter`....)

**Comment by minrk** [comment]
Not stupid at all! That just changed. The transition takes some getting used to.

**Comment by alexvorobiev** [comment]
Is there any way to use other directory than /etc/jupyter for system-wide jupyter_notebook_config.py?

**Comment by minrk** [comment]
@alexvorobiev depends. Do you want to prevent users from having their own config files?

**Comment by mogthesprog** [comment]
I realise this thread is a little stale now, but i just wanted to give my two cents. 

Since the notebook servers inherit their environment from jupyterhub, it means that since the hub is run as root (for auth purposes) the notebooks have the root environment. Is this behaviour intended? If not then I'm wondering whether it might be better to load the environment of the username that the jupyter notebook is using to spawn the process.

Have you got any thoughts on this?

The reason why i'm asking is that we have a bunch of command line tools (oracle client) for example, and when you try to use these either with python libraries (cx_oracle), or by shelling out of python with os.system or some other method, the binaries or libraries aren't available.This can be quite problematic in some cases.

**Comment by alexvorobiev** [comment]
@minrk I just want to keep all configuration files for Jupyter in the same place..

@mogthesprog I have a similar problem - our user set tons of environment variables in their login scripts. I have been wondering if it is possible to use the kernel.json to launch kernels through something like `/bin/bash --login -c` which would take care of all the environment settings.

**Comment by minrk** [comment]
If you make a script that looks like:

```bash
#!/usr/bin/env bash
# setup env
exec python -m ipykernel $@
```

It should load all the user's shell environment before instantiating the kernel. The `exec` is important, to get process replacement, rather than launching a subprocess. Point your kernelspec argv to this script (replacing the `python -m ipykernel` part with the path to this script).

**Comment by alexvorobiev** [comment]
I created a kernel for R which does the `/bin/bash --login -c` thing and it works as expected. Basically that's what RStudio server is doing. Now I wish somebody would figure out how to solve #331 to fully replicate the environment our users are getting on command line.

**Comment by mpetroff** [comment]
I had a similar problem, and @minrk's script mostly worked for me, but I needed to change the shebang line to `#!/bin/bash -i` to force an interactive shell so `.bashrc` would actually be applied.

**Comment by rcompton** [comment]
@minrk could you clarify

> Point your kernelspec argv to this script (replacing the python -m ipykernel part with the path to this script).

?
Do you mean I add an `argv` field to kernel.json?

**Comment by minrk** [comment]
@rcompton yes, I mean editing the `argv` field in the kernel.json. It probably looks like this:

```json
{
 "argv": [
  "/prefix/bin/python",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ],
 "language": "python",
 "display_name": "Python 3"
}
```

After you create `/path/to/your/script`, it will look like this:

```json
{
 "argv": [
  "/path/to/your/script",
  "-f",
  "{connection_file}"
 ],
 "language": "python",
 "display_name": "Python 3"
}
```

**Comment by RoyiAvital** [comment]
Let's say the same user has 2 different `conda` environments (Let's say `env001` and `env002`).
How could each has its own settings file?

**Comment by kashirin-alex** [comment]
a useful procedure/setting can be added to the Kernel specs

A Macro for filling with the token **NOTEBOOK_{APP,CONTAINER}_ID_PATH**, while these PATHS are available in the os.environ['LOCAL_DIRS'] - for pre-extracting to the Kernel execution.
the macro can be in-form like the ``` "{connection_file}" ``` to the ```  "argv" ```

The result, it will be use-full in this form,
```json
{
 "argv": [
  "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:{NOTEBOOK_APP_ID_PATH}",
  "/path/to/your/script",
  "-f",
  "{connection_file}"
 ],
 "language": "python",
 "display_name": "Python 3"
}
````

the problem and the reason, the APP_ID/CONTAINER_ID paths are dynamic with Spawner such as the Yarn and to have a FIXED-PATH preset is not an option.
