### ISSUE TITLE
ace editor is better than codemirror

### ISSUE THREAD

**Issue by cailiang9** [jupyter/jupyterhub#234]
why do jupyterhub uses codemirror editor?
for example:
1. the syntax for coffeescript does not support something like "test #{varible}"
2. it doesn't support in-html coffeescript syntax highlight either.

ace editor do support 1 and may also support 2.

**Comment by minrk** [comment]
JupyterHub doesn't include any editor itself, it only proxies requests to Jupyter Notebook instances, which happen to use CodeMirror. The decision is largely historical, and was made quite some time ago when ACE couldn't be instantiated multiple times on a page, which was a requirement for the notebook. The full-page text editor that was added recently uses CodeMirror because depending on multiple editors seems a bit silly.

If you have bug reports or feature requests for CodeMirror, they can be sent to the CodeMirror repo.

**Comment by cailiang9** [comment]
Thanks for explanation! if ace is fix and can be instantiated multiple times, could jupyter switch to use ace?

**Comment by minrk** [comment]
Theoretically, yes, but it's not likely to happen any time soon. We have many much higher priorities.
