### ISSUE TITLE
server works well as local host but fails to 'start proxy'

### ISSUE THREAD

**Issue by gpillemer** [jupyter/jupyterhub#271]
Can you help me diagnose, this was working initially, but broke once i had some issues trying to get docker spawner working. now it is not working with its default configuration. 

```

[I 2015-07-10 21:53:18.643 JupyterHub app:619] Not using whitelist. Any authenticated user will be allowed.
[I 2015-07-10 21:53:18.664 JupyterHub app:997] Hub API listening on http://localhost:8081/hub/
[I 2015-07-10 21:53:18.670 JupyterHub app:754] Starting proxy @ http://*:8000/
21:53:18.834 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
21:53:18.838 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
[C 2015-07-10 21:53:19.686 JupyterHub app:1003] Failed to start proxy
    Traceback (most recent call last):
      File "/home/gpillemer/jupyterhub/dockerspawner/src/jupyterhub/jupyterhub/app.py", line 1001, in start
        yield self.start_proxy()
      File "/home/gpillemer/jupyterhub/dockerspawner/src/jupyterhub/jupyterhub/app.py", line 775, in start_proxy
        _check()
      File "/home/gpillemer/jupyterhub/dockerspawner/src/jupyterhub/jupyterhub/app.py", line 771, in _check
        raise e
    RuntimeError: Proxy failed to start with exit code 8

[gpillemer@cloud-server-16 jupyterhub]$
```

**Comment by minrk** [comment]
Can you share your jupyter config? It loots like it's trying to bind to an invalid address.

**Comment by gpillemer** [comment]
thanks - i was actually trying to start the server with --ip='*', which i use with the ipython noteboiok
starting it and specifying the ip, i.e ip=xx.xx.xxx.xx works perfectly. thanks

**Comment by pulkitag** [comment]
I am getting a similar error - works well on locally, but with proxy. Any pointers on what might be going on?

[I 2015-10-02 08:08:45.461 JupyterHub app:1031] Hub API listening on http://localhost:8081/hub/
[C 2015-10-02 08:10:52.627 JupyterHub app:1037] Failed to start proxy
    Traceback (most recent call last):
      File "/home/ubuntu/pkgs/jupyterhub/jupyterhub/app.py", line 1035, in start
        yield self.start_proxy()
      File "/home/ubuntu/pkgs/jupyterhub/jupyterhub/app.py", line 755, in start_proxy
        if self.proxy.public_server.is_up() or self.proxy.api_server.is_up():
      File "/home/ubuntu/pkgs/jupyterhub/jupyterhub/orm.py", line 118, in is_up
        socket.create_connection((self.ip or 'localhost', self.port))
      File "/usr/lib/python3.4/socket.py", line 512, in create_connection
        raise err
      File "/usr/lib/python3.4/socket.py", line 503, in create_connection
        sock.connect(sa)
    TimeoutError: [Errno 110] Connection timed out

**Comment by zoltan-fedor** [comment]
I have the same / similar issue. Did you ever figure it out?

[I 2015-12-11 22:53:37.322 JupyterHub app:1031] Hub API listening on http://abc.com:8081/hub/
[C 2015-12-11 22:53:37.324 JupyterHub app:1037] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/jupyterhub/app.py", line 1035, in start
        yield self.start_proxy()
      File "/usr/lib/python3.5/site-packages/jupyterhub/app.py", line 755, in start_proxy
        if self.proxy.public_server.is_up() or self.proxy.api_server.is_up():
      File "/usr/lib/python3.5/site-packages/jupyterhub/orm.py", line 118, in is_up
        socket.create_connection((self.ip or 'localhost', self.port))
      File "/usr/lib64/python3.5/socket.py", line 707, in create_connection
        raise err
      File "/usr/lib64/python3.5/socket.py", line 698, in create_connection
        sock.connect(sa)
    OSError: [Errno 101] Network is unreachable

**Comment by minrk** [comment]
Are you using a DNS name for the proxy or an IP address?

**Comment by zoltan-fedor** [comment]
DNS name.

**Comment by minrk** [comment]
It looks like the DNS name isn't getting handled properly. Can you `curl` anything from that URL from where the Hub is running?

**Comment by zoltan-fedor** [comment]
It is all running on one server. I did run a python http server on it with
no problem.
But anyhow I will also try it with ip and report back in 2 hours.

**Comment by zoltan-fedor** [comment]
I have switched to IP, but unfortunately the issue is the exact same.
I do code a lot in Python and I have a feeling that this is the usual Python proxy issue - namely that when you have proxy settings in the user profile in unix to access the internet then Python's socket library automatically picks that up and tries to send all traffic to that proxy, even the local ones.
I will test and make changes to the code to verify, but if it turns out to be this, then that will likely require some code change to correct.


[I 2015-12-14 14:34:39.763 JupyterHub app:1031] Hub API listening on http://10.xx.xx.xx:8081/hub/
[C 2015-12-14 14:34:39.766 JupyterHub app:1037] Failed to start proxy
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/jupyterhub/app.py", line 1035, in start
        yield self.start_proxy()
      File "/usr/lib/python3.5/site-packages/jupyterhub/app.py", line 755, in start_proxy
        if self.proxy.public_server.is_up() or self.proxy.api_server.is_up():
      File "/usr/lib/python3.5/site-packages/jupyterhub/orm.py", line 118, in is_up
        socket.create_connection((self.ip or 'localhost', self.port))
      File "/usr/lib64/python3.5/socket.py", line 707, in create_connection
        raise err
      File "/usr/lib64/python3.5/socket.py", line 698, in create_connection
        sock.connect(sa)
    OSError: [Errno 101] Network is unreachable

**Comment by zoltan-fedor** [comment]
I have managed to resolve this.

I had created the jupyterhub_config.py file (instead of supplying server ip / server name as command line parameter) and set the proxy_api_ip, ip, and hub_ip to the same ip address, the ip of the server and now it starts fine.

[I 2015-12-14 16:18:35.002 JupyterHub app:1031] Hub API listening on http://10.xx.xx.xx:8081/hub/
[I 2015-12-14 16:18:35.006 JupyterHub app:788] Starting proxy @ http://10.xx.xx.xx:8000/
16:18:35.116 - info: [ConfigProxy] Proxying http://10.xx.xx.xx:8000 to http://10.xx.xx.xx:8081
16:18:35.118 - info: [ConfigProxy] Proxy API at http://10.xx.xx.xx:8001/api/routes
[I 2015-12-14 16:18:35.211 JupyterHub app:1054] JupyterHub is now running at http://10.xx.xx.xx:8000/

**Comment by zoltan-fedor** [comment]
Now it has another problem - when connecting tot he spawned instance. I guess because it is spawing with "--ip=localhost" instead of "--ip=[IP]".
Any idea where to change this in the config. I have already set he proxy_api_ip, ip and hub_ip in the config to the actual server ip.


[I 2015-12-14 16:24:06.545 JupyterHub log:100] 200 GET /hub/login (@10.xx.xx.45) 21.80ms
[I 2015-12-14 16:24:13.138 JupyterHub spawner:363] Spawning jupyterhub-singleuser --user=zoltan.fedor --port=38020 --cookie-name=jupyter-hub-token-zoltan.fedor --base-url=/user/zoltan.fedor --hub-prefix=/hub/ --hub-api-url=http://10.xx.xx.xx.9:80/hub/api --ip=localhost
[W 2015-12-14 16:24:13.188 JupyterHub utils:76] Failed to connect to http://localhost:38020/user/zoltan.fedor ([Errno 101] Network is unreachable)

**Comment by zoltan-fedor** [comment]
Found it, c.Spawner.ip

**Comment by minrk** [comment]
@zoltan-fedor so it looks like `localhost` is broken on your machine. Any idea as to what might be the cause of that? We've seen it reported intermittently, but I haven't been able to work out the cause. It seems like a pretty significant problem in the local system configuration.

**Comment by minrk** [comment]
@zoltan-fedor can you run this code:

```python
#!/usr/bin/env python3
import socket
import warnings
from threading import Thread

def localhost():
    """Return localhost or 127.0.0.1"""
    if hasattr(localhost, '_localhost'):
        return localhost._localhost
    binder = connector = None
    try:
        binder = socket.socket()
        binder.bind(('localhost', 0))
        binder.listen(1)
        port = binder.getsockname()[1]
        def accept():
            try:
                conn, addr = binder.accept()
            except ConnectionAbortedError:
                pass
            else:
                conn.close()
        t = Thread(target=accept)
        t.start()
        connector = socket.create_connection(('localhost', port), timeout=10)
        t.join(timeout=10)
    except (socket.error, socket.gaierror) as e:
        warnings.warn("localhost doesn't appear to work, using 127.0.0.1\n%s" % e, RuntimeWarning)
        localhost._localhost = '127.0.0.1'
    else:
        localhost._localhost = 'localhost'
    finally:
        if binder:
            binder.close()
        if connector:
            connector.close()
    return localhost._localhost
print(localhost())
```

and tell me what you get?

**Comment by zoltan-fedor** [comment]
This seemed to have worked, because when running this code I got back "localhost".

**Comment by zoltan-fedor** [comment]
Found the issue.
It is the hosts file. I am using Oracle Linux 7, but also checked on Oracle Linux 6, CentOS 6, etc and it seems all of them has the following in the hosts file (/etc/hosts):

`127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4`
`::1         localhost localhost.localdomain localhost6 localhost6.localdomain6`

The line start with `::1` is causing the issue with the socket library of Python not being able to connect to 'localhost' but throwing the `Network is unreachable` error.

So if your /etc/hosts is:
`127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4`
`::1         localhost localhost.localdomain localhost6 localhost6.localdomain`

Then the following code:
`import socket`
`socket.create_connection(('localhost', 12121))`

Will throw:
```Traceback (most recent call last):
  File "test2.py", line 2, in <module>
    socket.create_connection(('localhost', 12121))
  File "/usr/lib64/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 101] Network is unreachable```

If you change `localhost` to `127.0.0.1` in your code, then obviously it works.
Also if you remove that line starting with `::1` from your /etc/hosts file, then the code works with `localhost`

As such my suggestion is to change the code in /jupyterhub/orm.py line 117 from:
`socket.create_connection((self.ip or 'localhost', self.port))`
to
`socket.create_connection((self.ip or '127.0.0.1', self.port))`

Obviously it is still a question why the socket library throws this error...
