### ISSUE TITLE
How to run jupyterhub from the start

### ISSUE THREAD

**Issue by dbuendiab** [jupyter/jupyterhub#317]
I'm running an Amazon instance for jupyterhub. I've got it working with:

```bash
cd /etc/jupyterhub
sudo -u rhea jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner
```

I'm not very used with Linux, and would like to know where can I put those commands to get jupyterhub on at start. In Windows there was in times an **autoexec.bat** file to initialize. What is the equivalent one or similar for Linux?

**Comment by willingc** [comment]
@dbuendiab Passing this along to @minrk, @rgbkrk, and @jhamrick for suggestions.

Related to #313 for future reference and doc enhancements.

**Comment by jhamrick** [comment]
I think probably the way you need to do it is with systemd, which manages services on linux. Check out this answer on stackexchange for an example of how to use systemd to start a script at boot:

http://unix.stackexchange.com/questions/47695/how-to-write-startup-script-for-systemd

And the full documentation on the options you can use, some of which are mentioned in that answer:

http://www.freedesktop.org/software/systemd/man/systemd.service.html

Someone else might have already written a script like this for systemd (maybe @minrk has?) but I'm not sure. If not, and if you end up getting it to work with systemd, do please share your script with us so we can point other people to it in the future as well :smile:

**Comment by minrk** [comment]
I've used supervisord the most, which looks like this (in `/etc/supervisor/conf.d/jupyterhub.conf`):

```ini
[program:jupyterhub]
user=root
command=python3 -m jupyterhub -f /etc/juptyerhub/jupyterhub_config.py
directory=/srv/jupyterhub
autostart=true
autorestart=true
startretries=1
exitcodes=0,2
stopsignal=TERM
redirect_stderr=true
stdout_logfile=/var/log/jupyterhub.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
```

**Comment by jetheurer** [comment]
@minrk how do you start that supervisord?  I'm getting an `ERROR (no such process)` with `supervisorctl start jupyterhub`

**Comment by minrk** [comment]
I think `supervisorctl reload` loads the config files

**Comment by yuvipanda** [comment]
The following systemd unit should also work:

    [Unit]
    Description=Jupyterhub
    
    [Service]
    User=root
    ExecStart=/usr/local/bin/jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner
    
    [Install]
    WantedBy=multi-user.target

You can put that in `/lib/systemd/system/jupyterhub.service`, reload it with `systemctl daemon-reload` and start it with `systemctl start jupyterhub`. Can change the User property to whatever user you want it to be. You can then see logs with `journalctl -u jupyterub`

**Comment by arnome** [comment]
Hi,
for me (`GNU/Linux Debian 8 Jessie, jupyterhub --version : 0.5.0`), this `jupyter.service` works much better : 
```
> $ cat /etc/systemd/system/jupyterhub.service                                                                                                                                                       
[Unit]
Description=Jupyterhub
After=syslog.target network.target

[Service]
User=root
ExecStart=/usr/local/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py

[Install]
WantedBy=multi-user.target
```

For the jupyter_config.py I follow the _[JupyterHub Documentation
Release 0.6.0.dev](https://media.readthedocs.org/pdf/jupyterhub/latest/jupyterhub.pdf)_

arnome

**Comment by yourinoelnelson** [comment]
```
#!/usr/bin/env bash
# /srv/jupyterhub/launch.sh
set -e
source env
exec jupyterhub $@
```
When I run the launch.sh file included above ( I got it from the tutorial) I get the following error:

> launch.sh: line 4: source: /usr/bin/env: cannot execute binary file

I am running Centos 7. For whatever reason that `source env` is causing an error, any idea why?

Thank you for your help.

**Comment by vhp1360** [comment]
Hi,
I tried to ran 

> jupyterhub

 as service  in 

> CentOS7

according [Run jupyterhub as a system service](https://github.com/jupyterhub/jupyterhub/wiki/Run-jupyterhub-as-a-system-service) after i ran
```
service jupyterhub start
service jupyterhub status
```
below messages were appear :-)
> Redirecting to /bin/systemctl status  jupyterhub.service
● jupyterhub.service - Jupyterhub
   Loaded: loaded (/usr/lib/systemd/system/jupyterhub.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2016-10-03 19:05:05 IRST; 4s ago
  Process: 40071 ExecStart=/usr/bin/jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner (code=exited, status=1/FAILURE)
 Main PID: 40071 (code=exited, status=1/FAILURE)
> 
> Oct 03 19:05:04 cloud.shomara jupyterhub[40071]: Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
Oct 03 19:05:04 cloud.shomara jupyterhub[40071]: Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
Oct 03 19:05:04 cloud.shomara jupyterhub[40071]: [W 2016-10-03 19:05:04.932 JupyterHub app:757] No admin users, admin interface will be unavailable.
Oct 03 19:05:04 cloud.shomara jupyterhub[40071]: [W 2016-10-03 19:05:04.933 JupyterHub app:758] Add any administrative users to `c.Authenticator.admin_users` in config.
Oct 03 19:05:04 cloud.shomara jupyterhub[40071]: [I 2016-10-03 19:05:04.933 JupyterHub app:785] Not using whitelist. Any authenticated user will be allowed.
Oct 03 19:05:04 cloud.shomara jupyterhub[40071]: [I 2016-10-03 19:05:04.956 JupyterHub app:1231] Hub API listening on http://127.0.0.1:8081/hub/
Oct 03 19:05:04 cloud.shomara jupyterhub[40071]: [E 2016-10-03 19:05:04.962 JupyterHub app:963] Refusing to run JuptyterHub without SSL. If you are terminating SSL...n on HTTP.
Oct 03 19:05:05 cloud.shomara systemd[1]: jupyterhub.service: main process exited, code=exited, status=1/FAILURE
Oct 03 19:05:05 cloud.shomara systemd[1]: Unit jupyterhub.service entered failed state.
Oct 03 19:05:05 cloud.shomara systemd[1]: jupyterhub.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

finally i found [Setting up Jupyterhub with sudospawner and Anaconda](https://medium.com/@ybarraud/setting-up-jupyterhub-with-sudospawner-and-anaconda-844628c0dbee#.pxpe7lodx) and ran `pip install git+https://github.com/jupyter/sudospawner` it works properly.

**Comment by willingc** [comment]
Thanks @vhp1360. :cake: I've added the post you referenced to the [community section of the wiki](https://github.com/jupyterhub/jupyterhub/wiki/Community-Deployment-Notes) since it may help others too.

**Comment by ankanheesun** [comment]
Hi all, 

I did everything follow the guide to write a system service for Jupyter, I am on CentOS 7.3, node 6.11.0, npm 3.10.10 and python 3.6.1. 

Actually, I started JupyterHub successfully using the command line 

> /opt/python/bin/jupyterhub -f /etc/jupyterhub/jupyterhub_config.py

But when I did it from system service, it didn't work. 
![screen shot 2017-06-15 at 11 47 20](https://user-images.githubusercontent.com/8588922/27175758-8352cfc8-51c0-11e7-94e8-e3629ab6d709.png)

**Comment by minrk** [comment]
Most often, failure to start as a service when starting by hand works is due to the extremely minimal environment (especially PATH) that services start out with by default. You will likely need to specify the PATH you want to use that has `configurable-http-proxy` and `jupyterhub` on it.

**Comment by ufJmacca** [comment]
Hi All,

I have just created an Ubuntu 16.04 server to run jupyterhub on, however while setting jupyterhub as a service, i notice that it does not seem to be referencing my original jupyterhub_config.py file which I worked so hard on setting up, especially re. ssl. 

When i was running it via calling jupyterhub it would run with ssl as per my config file, but now that it is a system it seems to be using a different config file that I cannot find.

Any assistance would be greatly appreciated, below is the  used in `/lib/systemd/system/jupyterhub.service` and `/etc/systemd/system/jupyterhub.service`, and yes I did attempt to change the referenced config file to the one I created, but the service would not load, giving error code 1

> [Unit]
> Description=Jupyterhub
> 
> [Service]
> User=root
> Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/anaconda3/bin"
> ExecStart=/usr/local/bin/jupyterhub -f /home/ubuntu/jupyterhub_config.py
> 
> [Install]
> WantedBy=multi-user.target
>

**Comment by bikashdube** [comment]
@ufJmacca Your problem is also possibly due to insufficient /path/to/configurable-http-proxy. Let the Environment="PATH=..." find it.

**Comment by vhp1360** [comment]
Hi @ufJmacca ,
why do not put _Path _ in _/etc/profile_ or export it?

**Comment by jhermann** [comment]
FYI, I'm about to release a first version of my Debian package at https://github.com/1and1/debianized-jupyterhub, including systemd support and everything for a setup not running as root.

**Comment by bacloud14** [comment]
Following wiki: 

I am getting:

`● jupyterhub.service - LSB: Start jupyterhub
   Loaded: loaded (/etc/init.d/jupyterhub; generated)
   Active: inactive (dead)
     Docs: man:systemd-sysv-generator(8)

Dec 20 09:02:45 instance-20191219-1901 systemd[1]: Starting LSB: Start jupyterhub...
Dec 20 09:02:45 instance-20191219-1901 systemd[1]: Started LSB: Start jupyterhub.
Dec 20 09:02:54 instance-20191219-1901 systemd[1]: Stopping LSB: Start jupyterhub...
Dec 20 09:02:54 instance-20191219-1901 systemd[1]: Stopped LSB: Start jupyterhub.`

when running `systemctl status jupyterhub`
