### ISSUE TITLE
Spawner poll return value during spawn

### ISSUE THREAD

**Issue by betatim** [jupyter/jupyterhub#428]
This is a question about how `start_timeout` and `slow_spawn_timeout` work together.

In `BaseHandler.spawn_single_user()` `user.spawn()` is called which should complete with in `start_timeout` I think. On line 296 the `slow_spawn_timeout` is used, which is much shorter. If we reach the timeout then `user.spawner.poll()` is called and if it is not `None` an exception is raised.

My expectation would be that `user.spawner.poll()` returns something that isn't `None` while still spawning, as it isn't yet running. However this means you effectively only have `slow_spawn_timeout` seconds to be done spawning.

Should `poll()` already return `None` while still spawning?

**Comment by minrk** [comment]
Since `Spawner.poll()` took its inspiration from `Popen.poll()`, the interpretation of its return value is:

- None: has not exited
- integer: exit code

So `poll` really means "Has it exited?" and None means "No, it has not exited." even if the reason is that it has not actually finished starting, since it doesn't make a difference *why* it hasn't exited.

As it is interpreted now, poll should return None from the moment `Spawner.start` has been called to the time that the server has stopped.

The slow spawn timeout is used to show an HTML page to the user before HTTP timeouts / human patience would give up, but the spawner is still allowed to continue. The reason poll is called after the slow timeout is a check for "is the reason it's taking so long to start really that it died already?" The 'true' spawn timeout is used to actually give up and destroy the spawner so you can try again later.

**Comment by minrk** [comment]
#442 should ensure that poll will never be called before start has returned, so the question should be easier to answer.
