### ISSUE TITLE
Spawner custom form validation

### ISSUE THREAD

**Issue by betatim** [jupyter/jupyterhub#439]
Are there ideas for allowing form validation for spawners that have a custom form?

I was thinking of raising an exception in `options_from_form()` and moving the `try` up by one line in [SpawnHandler](https://github.com/jupyter/jupyterhub/blob/master/jupyterhub/handlers/pages.py#L97).

**Comment by minrk** [comment]
I was assuming that options would be validated in `Spawner.start`, since those options can come from two places: Spawner form and JSON API. Only when they come from the form do they need transforming from dumb form format to a reasonable object. An error raised in start should propagate to the spawn form page.

No harm in putting options_from_form into the try block, though (#443)
